# This is the main file that describes the API. It contains the paths and the operations that can be performed on them.
openapi: 3.0.0
info:
  title: Quotes API
  description: This is a simple API that returns quotes.
  version: 1.0.0
servers:
  - url: http://localhost:8080
components:
  schemas:
    Quote:
      type: object
      properties:
        id:
          type: integer
paths:
  /quotes:
    get:
      summary: Get all quotes
      operationId: getQuotes
      responses:
        '200':
          description: A list of quotes
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Quote'
  /quotes/{id}:
    get:
      summary: Get a quote by ID
      operationId: getQuoteById
      parameters:
        - name: id
          in: path
          required: true
          description: The ID of the quote to get
          schema:
            type: integer
      responses:
        '200':
          description: A single quote
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Quote'